modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"
[[mods]]
modId = "momlove"
version = "${file.jarVersion}"
displayName = "MomLove"
authors = [
    "cnlimiter",
    "Rinko1231",
    "Tapio"
]
description = '''

'''
